### ISSUE TITLE
[Enhancement] Dark themed media elements

### ISSUE THREAD

**Issue by Xaero252** [kaytotes/ImprovedBlizzardUI#100]
Wasn't sure the best way to submit this to you; so I'm posting here. 
I've taken the "Dark" LortiUI style elements and made them compatible with your addon. It would probably be a nice addition to have a switch between "stock" and "dark", here's a link to a zip containing the *.BLP files for the dark change. Anybody reading this who wants to give them a shot, replace the *.BLP files found in
<WoW>\Interface\Addons\ImprovedBlizzardUI\media
https://drive.google.com/open?id=12xQmRNl5Q7F8qRP2fllEgKRXrUSXlPDn

**Comment by kaytotes** [comment]
I have a backup of these files but nonetheless will be closing this issue.
