### ISSUE TITLE
Player frame health bar bugged when entering vehicles

### ISSUE THREAD

**Issue by Xaero252** [kaytotes/ImprovedBlizzardUI#101]
This is due to the BlizzardInterfaceCode no longer calling PlayerFrameHealthBar:SetHeight() on entering a vehicle. Since we've modified the height and they aren't modifying it back anymore, this leads to the healthbar escaping the bounds of the vehicle frame.

Solution is simple, add event handling for UNIT_ENTERED_VEHICLE and call PlayerFrameHealthBar:SetHeight() there to an appropriate value. I'm testing with 13 currently, to see if that fits things correclty.

**Comment by Xaero252** [comment]
Here's a screenshot of the issue:
https://imgur.com/a/plheJiR
As you can see the text is aligned correctly, but the size of it, and hte heatlhbar itself completely escape the bounds of the vehicle unitframes. I am using a dark-recolor of the frames but the dimensions are identical to the original frames. 
Also note the micromenu bug visible here, I'll probably just forcibly hide it as I have another menu I use instead. Simply resizing/positioning on UNIT_ENTERED_VEHICLE doesn't work due to the issue mentioned above with situations like that found in Seething Shore where the UNIT_ENTERED_VEHICLE event fires, but the unitframe texture remains untouched.

**Comment by kaytotes** [comment]
This is a pretty glaring issue now with BfA and the Tortollan emissary quests. I want to get this fixed before raids are out.
