### ISSUE TITLE
Stack action bars and move party frame.

### ISSUE THREAD

**Issue by sipso** [kaytotes/ImprovedBlizzardUI#103]
Would you consider stacking the bottom actionbars ontop of each other? Like it was in pre 8.0? Also an option to move party frames (or any frames) would be nice. As of now, party frames really crowd the center of my screen in aoe fights as tank, when i'm often put against the wall and camera gets real close.

**Comment by kaytotes** [comment]
The intention is to go back to that style however going to require a decent amount of work. Details here https://github.com/kaytotes/ImprovedBlizzardUI/issues/98

More options like that are intended long term.
