### ISSUE TITLE
Guild Controls Error

### ISSUE THREAD

**Issue by Arcthor87** [kaytotes/ImprovedBlizzardUI#104]
Hello Kaytotes! I just found this, and am really loving using your setup. The only issue i have had is that i am a guild leader, and when attempting to change any characters rank within the guild, i get the error "Improved Blizzard UI has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI." this message then has a "Disable" and an "Ignore" button.

**Comment by kaytotes** [comment]
I've noticed some taint issues leading to this and achievement frames and will be taking a look.
