### ISSUE TITLE
tooltip font adjustments should respect config toggles

### ISSUE THREAD

**Issue by killarny** [kaytotes/ImprovedBlizzardUI#105]
Currently there doesn't appear to be a way to disable the adjustments made to the font for tooltips. The config has a toggle called "Style Tooltips" that implies it'll stop changing the fonts if I turn it off, but this doesn't seem to be working properly.

Here's a tooltop in Vanilla WoW with no addons (with the interface settings showing to prove that there are no other addons loaded):

![vanilla-tooltip](https://user-images.githubusercontent.com/29001/44567782-03e7c080-a742-11e8-9907-62b2b0a851a6.png)

Here is the exact same tooltip, with only Improved Blizzard UI loaded, and all the tooltip options toggled off:

![ibi-tooltip](https://user-images.githubusercontent.com/29001/44567813-1eba3500-a742-11e8-8a9b-2269267764b0.png)

Hopefully this is unintended behavior, but if not could we please have the option to disable all tooltip changes made by this addon?

**Comment by kaytotes** [comment]
Thank you for this report. I'm going to be taking a pass through the entire UI and clearing up these config issues.
