### ISSUE TITLE
Auto-Sell Greys missing items

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/ImprovedBlizzardUI#107]
I've noticed while leveling in BfA that i'm having to close and reopen vendor windows a few times if I have a load of a grey items in my bags. Unsure what the specific cause is as in theory this didn't change with BfA.

I do use BaudBag. Maybe that is a cause so will test without that first.

**Comment by kaytotes** [comment]
Well that at the very least confirms it. I'll be taking a look.

**Comment by Misunderstood-Wookiee** [comment]
Assume this is still a valid issue, may take look into it on my fork, otherwise for now since I also use the recommend add-ons besides Story I could just toggle auto sell-off in this and on in baudbags,
