### ISSUE TITLE
Team panel cannot be displayed

### ISSUE THREAD

**Issue by hiccup711** [kaytotes/ImprovedBlizzardUI#109]
Why can't I see my team panel? Is there any way to adjust?

**Comment by kaytotes** [comment]
I'm unsure what you mean by Team Panel?

**Comment by hiccup711** [comment]
[https://imgurl.org/temp/1809/9d997872fd96e9ba.png ](url)
Like this, I can't see the icon of my teammates.

**Comment by kaytotes** [comment]
I'm unsure why you can't see that. There is no config or hiding. Do you get any errors?

**Comment by kaytotes** [comment]
I can not reproduce this.
