### ISSUE TITLE
BfA Maintenance Mode

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/ImprovedBlizzardUI#114]
Well, I'm no longer playing BfA as of a couple weeks ago due to my dissatisfaction with the game. 

Due to this most existing issues with regards to the 8.0 BfA build will not be fixed unless done by an exterior and pull requested.

**Comment by Misunderstood-Wookiee** [comment]
But this Ui is amazeballs, been using it over bartender or that hideous ElvUi. 
Was testing out AzeriteUi Beta but that is a long way off being polished for a daily, Good thing I forked this.

**Comment by kaytotes** [comment]
If you have a fork you are maintaining feel free to PR fixes. Obviously if
I'm not playing I can't easily both find and fix issues.

On 30 Sep 2018 15:00, "Misunderstood-Wookiee" <notifications@github.com>
wrote:

But this Ui is amazeballs, been using it over bartender or that hideous
ElvUi.
Was testing out AzeriteUi Beta but that is a long way off being polished
for a daily, Good thing I forked this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kaytotes/ImprovedBlizzardUI/issues/114#issuecomment-425722898>,
or mute the thread

**Comment by Misunderstood-Wookiee** [comment]
Indeed I am maintaining a fork being my first wow addon really but so far things have been working.
trying to add a new module atm, tho unsure how to get it to register correctly as simply loading the module throws the lua error "Error Loading"

**Comment by Misunderstood-Wookiee** [comment]
@kaytotes You would not happen to have a template for getting a new lua file too do something when a checkbox in the addons options menu is ticked or unticked, would you?

I have the code I need to run I am just not sure how to actually get it to detect the checkbox, the checkbox is already visible in the addons misc options.

**Comment by Misunderstood-Wookiee** [comment]
@kaytotes Figured it out thanks, (it was easier than I had been screwing around doing for last four hours (sigh) I just had to strip one of the existing modules leaving just the framework (EventHandler) and change the function & Interface Label.

**Comment by kaytotes** [comment]
Please look at #122 for latest information.
