### ISSUE TITLE
Invalid LUA operation fix for Class Colours

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [kaytotes/ImprovedBlizzardUI#119]
https://github.com/Misunderstood-Wookiee/ImprovedBlizzardUIPlus/commit/86a2f37ed3385f3d4c21736aeff6d134f5b48d6d.

Sometimes the raid class colour cannot be found for the table during certain world events I noticed this during some pet battles and some during WOD intro scenarios while hovering over npcs nameplates. 

For what ever the cause internally this does rarely occur and we have to give it some default data so that the table values are not nil which causes and invalid LUA operation for the function which gets class colours.

Above a commit made to my fork of this project that should fix the error by using a default table (white colour) whenever the initial raid class colour is not found.

**Comment by Misunderstood-Wookiee** [comment]
I'll give a shot I'm not so great with PR or cherry picks. The repo I already did fork are you suggesting I fork it again and cherry pick my fork of that commit into his?

**Comment by kaytotes** [comment]
Thanks for this @Misunderstood-Wookiee I've pulled this in to what will be the latest build. https://github.com/kaytotes/ImprovedBlizzardUI/commit/1bdc752e95c7b17f98fcaafca2d936c988f3336f
