### ISSUE TITLE
Focus frame option

### ISSUE THREAD

**Issue by Wizeowel** [kaytotes/ImprovedBlizzardUI#121]
Hello!
Your addon is ideal for me, I like how it places the player and target frames. The party frames also look good, positioned nicely central, but not as close as the player frame. It's a shame the triple stacked action bars don't work anymore but 

However, I have a suggestion for the focus frame. When playing a healer I have several important weakauras that I want to place near each individual party member frame, but unfortunately the focus frame is in the way. 

Would it be possible to add a configuration option to choose to anchor the focus frame above the target instead? So that it's on the right side of the screen. Or am I overlooking some other UI elements that are often above the target?

Perhaps something like this ... focus.lua (85)
if (FramesDB.focusAnchorToTarget) then
 FocusFrame:SetPoint('LEFT', TargetFrame, 'TOP', -150, 90)
else
 FocusFrame:SetPoint('RIGHT', PlayerFrame, 'TOP', 150, 90)
end

**Comment by kaytotes** [comment]
This should be covered in the next release but needs testing. Going to keep this open for now however.

**Comment by Wizeowel** [comment]
Nice one! :-)
