### ISSUE TITLE
What is this UI?

### ISSUE THREAD

**Issue by MonsterChube** [kaytotes/ImprovedBlizzardUI#123]
![002](https://user-images.githubusercontent.com/46014169/50262443-629d1c80-044c-11e9-835d-9c3f9bc8ec93.png)
![001](https://user-images.githubusercontent.com/46014169/50262458-7052a200-044c-11e9-8cd6-cf838093e01c.png)

**Comment by kaytotes** [comment]
The Maelstrom bar for Shamans. Part of the base UI.
