### ISSUE TITLE
Is there Classic Wow version addon?

### ISSUE THREAD

**Issue by crispizza** [kaytotes/ImprovedBlizzardUI#132]
or Do you have any plan to develop classic version?

**Comment by kaytotes** [comment]
I do intend on porting to Classic WoW, and in fact going forwards that will be the "primary" version of the addon. I have no interest in retail.

**Comment by Kalinnka** [comment]
Is there any release date for the UI for classic?

**Comment by kaytotes** [comment]
Release Candidate now available here: https://github.com/kaytotes/ImprovedBlizzardUI_Classic/releases

Once I've had a bit more testing time this will be getting it's own addon page on Curse and WoWInterface.

Please post classic related issues to https://github.com/kaytotes/ImprovedBlizzardUI_Classic/
