### ISSUE TITLE
Garrison fix

### ISSUE THREAD

**Issue by Wizeowel** [kaytotes/ImprovedBlizzardUI#134]
Hi. When player is in the Garrison there are no map coords, so the addon spams an error.

This is because ImprovedBlizzardUI\modules\maps\minimap.lua only checks inInstance. However the Garrison - and maybe other shared indoor non-instance places - returns (false, "party") for the IsInInstance call

To fix, adjust line 32 of ImprovedBlizzardUI\modules\maps\minimap.lua
 `
            if (not inInstance and instanceType == 'none') then
`

**Comment by kaytotes** [comment]
Thanks for this. I will be generating and testing a new build in a couple days with this included.

**Comment by kaytotes** [comment]
This has now been resolved with 8.0.4
