### ISSUE TITLE
help guild tab allways pop lua error

### ISSUE THREAD

**Issue by Gvakoulas** [kaytotes/ImprovedBlizzardUI#137]
Message: Interface\FrameXML\UIDropDownMenu.lua:340: attempt to index local 'listFrame' (a nil value)
Time: Thu May  7 10:44:25 2020
Count: 1
Stack: Interface\FrameXML\UIDropDownMenu.lua:340: attempt to index local 'listFrame' (a nil value)
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:340: in function `UIDropDownMenu_AddButton'
[string "@Interface\AddOns\Blizzard_Communities\ClubFinder.lua"]:559: in function `initFunction'
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:76: in function `UIDropDownMenu_Initialize'
[string "@Interface\AddOns\Blizzard_Communities\CommunitiesSettings.lua"]:43: in function <...\AddOns\Blizzard_Communities\CommunitiesSettings.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:457: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:707: in function `Communities_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:973: in function `ToggleCommunitiesFrame'
[string "@Interface\FrameXML\UIParent.lua"]:828: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

Locals: info = <table> {
 checked = <function> defined @Interface\AddOns\Blizzard_Communities\ClubFinder.lua:507
 text = "Social & Leveling"
 minWidth = 190
 func = <function> defined @Interface\AddOns\Blizzard_Communities\ClubFinder.lua:508
 keepShownOnClick = false
}
level = 0
listFrame = nil
index = 1
width = nil
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:74
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 740
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 DetailsWindowOptionsBarTextEditorEntryNumberLines = DetailsWindowOptionsBarTextEditorEntryNumberLines {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 EncounterDetails_SpellAurasScrollScrollChildFrame = EncounterDetails_SpellAurasScrollScrollChildFrame {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:778
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 WorldQuestTrackerWorldMapPOIWorldQuestTrackerWorldSummarySquarePOI2BorderShineAnimation3 = WorldQuestTrackerWorldMapPO

**Comment by kaytotes** [comment]
I'm investigating this.

**Comment by Gvakoulas** [comment]
any news there ? :/  still didnt find anything

**Comment by kaytotes** [comment]
I can't figure out a solution. No idea.

**Comment by kaytotes** [comment]
This has now been resolved with 8.0.4
