### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Dooby112** [kaytotes/ImprovedBlizzardUI#138]
once i installed i noticed that my character, collections, achievments ETC buttons were taken away. i know this isnt a big issue because there are key binds for these things but it would be nice to get the clickable buttons back as i do not always remember the keybinds...

thank you for your time

**Comment by kaytotes** [comment]
The micro menu has become a button next to the action bars.

**Comment by Dooby112** [comment]
button is not there

**Comment by kaytotes** [comment]
Please verify what version of the addon you are using and provide a screenshot.
