### ISSUE TITLE
will you be updating ui and i a have this error 

### ISSUE THREAD

**Issue by Astinil** [kaytotes/ImprovedBlizzardUI#139]
Message: Interface\FrameXML\UIDropDownMenu.lua:340: attempt to index local 'listFrame' (a nil value)
Time: Sat May  9 15:41:25 2020
Count: 1
Stack: Interface\FrameXML\UIDropDownMenu.lua:340: attempt to index local 'listFrame' (a nil value)
[string "=[C]"]: ?
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:340: in function `UIDropDownMenu_AddButton'
[string "@Interface\AddOns\Blizzard_Communities\ClubFinder.lua"]:559: in function `initFunction'
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:76: in function `UIDropDownMenu_Initialize'
[string "@Interface\AddOns\Blizzard_Communities\CommunitiesSettings.lua"]:43: in function <...\AddOns\Blizzard_Communities\CommunitiesSettings.lua:34>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:457: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:707: in function `Communities_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:973: in function `ToggleCommunitiesFrame'
[string "@Interface\FrameXML\UIParent.lua"]:828: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

Locals:

**Comment by kaytotes** [comment]
Under investigation.

**Comment by Astinil** [comment]
how you go fixing it

**Comment by kaytotes** [comment]
I haven’t been able to find an easy fix and not the time to work on it currently.

**Comment by kaytotes** [comment]
This has now been resolved with 8.0.4
