### ISSUE TITLE
Class Order Hall bar interfering with UI

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/ImprovedBlizzardUI#14]
I believe that the Class Order Hall bar that appears at the top of the screen when in a class orderhall will be covering Buffs, Minimap, Resource Monitor.

![512341](https://cloud.githubusercontent.com/assets/7526918/16358983/ef82b6a2-3b1b-11e6-8646-170aa1a2bdbe.jpg)

I have no way of properly testing this myself but if I can get a screenshot of this with `/framestack` enabled and the cursor hovered over the bar then I can force the bar to appear on the PTR and work around that. 

Could either of you two possibly get me one? @val1n @ben2k1690

**Comment by ben2k1690** [comment]
I can't call `/framestack` so im not able to send you a screenshot with both things :/

**Comment by kaytotes** [comment]
Hmm, that's odd. Perhaps blizzard disabled it in the Beta but not on PTR.

**Comment by val1n** [comment]
Without ImprovedBlizzardUI /framestack is working.

![wowscrnshot_062716_103339](https://cloud.githubusercontent.com/assets/453772/16373662/95c90736-3c53-11e6-879e-25bf4d417542.jpg)

**Comment by kaytotes** [comment]
Thank you sincerely @val1n lots of information for me to work with.

**Comment by kaytotes** [comment]
https://github.com/kaytotes/ImprovedBlizzardUI/commit/43d94730bba7f4964e68a1ec39adee82dd665e94
