### ISSUE TITLE
Appearances Window Issue

### ISSUE THREAD

**Issue by Brich1533** [kaytotes/ImprovedBlizzardUI#140]
Just small issue here, when in the appearances window and the "Sets" tab. When you go to right click and make a set a "favorite", the game just glitches on the right click and no drop down appears. Therefore having to disable the addon and use normal blizzard wow ui and then right click and make a set a favorite. Very minor but just a little annoying.

**Comment by kaytotes** [comment]
This has now been resolved with 8.0.4
