### ISSUE TITLE
Swap Bags

### ISSUE THREAD

**Issue by val1n** [kaytotes/ImprovedBlizzardUI#15]
The "Swap Bags" Micro Menu option is not working.

![wowscrnshot_071316_002511](https://cloud.githubusercontent.com/assets/453772/16785877/d1c9a24c-4890-11e6-9f0b-1bb87548011a.jpg)

**Comment by kaytotes** [comment]
Fixed with https://github.com/kaytotes/ImprovedBlizzardUI/commit/0b575ecea1a43824593a39fd420940915fc278b0
