### ISSUE TITLE
Config screen throws errors when attempting to load

### ISSUE THREAD

**Issue by M2D474** [kaytotes/ImprovedBlizzardUI#153]
Please see attached text file.

 
[impblizzui.txt](https://github.com/kaytotes/ImprovedBlizzardUI/files/5395619/impblizzui.txt)

**Comment by kaytotes** [comment]
Have you upgraded to the latest Shadowlands release?

**Comment by M2D474** [comment]
Indeed. Running 9.0.1.36272 pre-patch.

**Comment by kaytotes** [comment]
I may need some more details on how you triggered this as I can not replicate it using the latest release of this addon.

**Comment by M2D474** [comment]
Looks like this was my bad. Did a code pull and I think I got the dev branch. Pulled down from wowinterface (couldn't find the updated version on Curse), and problems fixed! Apologies for all the confusion, man!

If I might ask a question, any thoughts on being able to bring back party frames? Been a user of this UI for 3 xpacs now, and I miss the way you crafted the party frames! Irrespective, appreciate all the hard work you have put into this addon. Thank you for all that you are doing to make the game enjoyable for us!

**Comment by kaytotes** [comment]
Now that shadowlands is out i'm definitely planning on looking into the party frames issue that exists on retail. Blizzard basically made the frames very very protected so it's a struggle whereas on Classic they haven't.
