### ISSUE TITLE
Tooltip not showing mythic IO

### ISSUE THREAD

**Issue by mmckie02** [kaytotes/ImprovedBlizzardUI#157]
Hello, I had to disable your nice tooltip just to see the mythic io scores. Is there a setting or something I can do to enable both your styled tooltip and the mythic io?

**Comment by kaytotes** [comment]
I believe this is related to https://github.com/kaytotes/ImprovedBlizzardUI/issues/156

I'm looking at a bit of a rework of how I do the tooltip handling to accommodate pretty much any tooltip mods. For now I'd recommend simply disabling the Style Tooltips option.

**Comment by mmckie02** [comment]
Thanks! I'll wait patiently till then. Is your main addon page on curse the best place to occasionally check to see when it's implemented?

**Comment by kaytotes** [comment]
WoWInterface always has gotten priority and with the transition to Overwolf may not be available on curse at all in future

**Comment by mmckie02** [comment]
I'll keep that in mind then, thanks!

**Comment by kaytotes** [comment]
@mmckie02 Release 3.2.0 will contain the fixes for this. I will be releasing it to WoWInterface and Curseforge tomorrow however if you want it early you can find it here https://github.com/kaytotes/ImprovedBlizzardUI/releases/tag/3.2.0
