### ISSUE TITLE
Almost none of it works?

### ISSUE THREAD

**Issue by Naatan** [kaytotes/ImprovedBlizzardUI#16]
The unit frames were moved but that's about it.

Toggling some of the prefs and pressing OK (at which point the UI reloads) makes no difference.

![image](https://cloud.githubusercontent.com/assets/278649/16993362/07e1e688-4e71-11e6-8e01-50c7cc3ca060.png)

**Comment by Naatan** [comment]
Fixed by manually installing (don't use WoWMatrix).

**Comment by kaytotes** [comment]
Hmm, I don't condone the use of WoWMatrix as I have honestly no idea how it has ended up there. Maybe they poll from WoWInterface but [here](http://www.wowinterface.com/downloads/info23299-ImprovedBlizzardUI.html#info) and this repository are the only official sources.
