### ISSUE TITLE
Vendor grey items over counted

### ISSUE THREAD

**Issue by Wizeowel** [kaytotes/ImprovedBlizzardUI#163]
Hi! In autosell.lua you have an outer loop to run 4 times, presumably to make selling grey items faster or in case of vendor lag. But then you are overcounting the total value of the items vendors. 

Easy fix to modify line 40 

if (i == 0) then copper = copper + ( price * count ); end

**Comment by kaytotes** [comment]
Will be fixed in next release. Thanks for the report.
