### ISSUE TITLE
Buff Bar Problems

### ISSUE THREAD

**Issue by Ecaidian** [kaytotes/ImprovedBlizzardUI#167]
Using latest version, attached screenshot to give an example of what I'm talking about.

Buffs past 7 start to do weird things like stack under one another, lose their timers, lose mouse-over tooltips, etc...

![image](https://user-images.githubusercontent.com/76637447/103163096-52507280-47c7-11eb-8ab1-d646faf12823.png)

**Comment by kaytotes** [comment]
Are you using any other addons?

I've been raiding pretty heavily since Nathria came out and haven't seen this occur.
