### ISSUE TITLE
Target unitframe HP does not match Nameplate/Real value

### ISSUE THREAD

**Issue by Smoothz624** [kaytotes/ImprovedBlizzardUI#170]
90% of the time it is correct value, but i am running only this addon with default options. fresh install both wow and addon, and for some reason, random from what i can tell, if you spam the target button while joining or leaving combat or from 2 players with different hp but same name. it will confuse which one you are targeting sometimes it will give me an HP value that doent match any mob around so idk were its getting this from.

**Comment by Smoothz624** [comment]
This is in retail wow

**Comment by Smoothz624** [comment]
![image](https://user-images.githubusercontent.com/20229829/109352980-b932ec00-7849-11eb-9dff-35d06dd45d5f.png)

**Comment by Smoothz624** [comment]
So it may be an interaction with the addon "MoveAnything" i can only replicate it with that enabled.

**Comment by kaytotes** [comment]
I have tried to replicate this but can not. 

My addon doesn't recalculate health or anything like that, only changes the font for the health. 

This is likely either a bug with the default UI that I just have not noticed or as you said an issue with MoveAnything.
