### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by HiddenSecret1** [kaytotes/ImprovedBlizzardUI#171]
I just saw that there was an update for this UI and I did the update, but for some reason Blizzard thinks it is out of date. I would recommend looking to see if you can update the code to match the new WoW patch. I haven't had any issues yet but this is something to consider.

**Comment by kaytotes** [comment]
This has been updated on Curse and WoWInterface. Curse has issues with up to 3 day delays for it to appear in the client however so out of my control.
