### ISSUE TITLE
minor issues with TBC beta release

### ISSUE THREAD

**Issue by maken30** [kaytotes/ImprovedBlizzardUI#176]
Hey mate, thanks for updating! 

Just noticed its double displaying guild names when hovering over characters, I cant seem to see an option to turn it off? 

Also a minor one but the chat box and the character health bar seem to be overlapping with the default UI scale?

**Comment by kaytotes** [comment]
I recommend putting your UI scale right down / near the bottom. That's supposed to be the Blizzard default. 

Will investigate the double guild issue.

**Comment by kaytotes** [comment]
@maken30 I have managed to identify the issue and will be releasing an update soon.
