### ISSUE TITLE
Settings Stuck in Default Mode

### ISSUE THREAD

**Issue by Backupoffmy** [kaytotes/ImprovedBlizzardUI#180]
When I toggle off the options i do not want, specifically the "Style Tooltips" option - which triggers the reload UI, it resets everything in the addon to default

**Comment by Backupoffmy** [comment]
I had to roll back a version to keep my preferred settings - otherwise, upon update, it triggers everything back to default and when I go to re-change it, it does not stay applied.

**Comment by kaytotes** [comment]
Resetting user preferences was unfortunately required to also fix a different issue the addon was having. 

However I'll investigate why it won't let you apply new ones. 

Which client?

**Comment by Backupoffmy** [comment]
Shadowlands. Newest version of the addon

**Comment by michalsniezko** [comment]
I am having the same issue with the latest version of the addon 3.5.0

**Comment by kaytotes** [comment]
I will investigate this tonight. Shouldn't be a hard fix.

**Comment by kaytotes** [comment]
This will be fixed with 3.5.1
