### ISSUE TITLE
Update the addon for the 9.1 patch

### ISSUE THREAD

**Issue by georgethejournalist** [kaytotes/ImprovedBlizzardUI#188]
The **9.1 patch** is out on the live servers now and as such the addon is reported as no-longer compatible. I am using it further without many issues (bug sack is catching a lot of exceptions from lua but I have yet to discern if any of them come from here :)) but it might be off-putting for less experienced users.

I am not sure whether this requires any more work than changing a version number in some config file and so am leaving the issue description very generic :)

**Comment by kaytotes** [comment]
This just needs me to bump the version number in the TOC. No huge rush. I've been playing 9.1 myself both on the PTR and now on live so I'm pretty sure nothing obvious is broken. 

I'll get around to this.
