### ISSUE TITLE
Chat is bugged (image in body)

### ISSUE THREAD

**Issue by NightDweller** [kaytotes/ImprovedBlizzardUI#19]
http://i.imgur.com/5rPLMGS.png

If i click on Combat Log, where you type moves over the tabs. This bug happens on NA but not on EU. Everything is set the same. Still happens if I load only ImprovedBlizzardUI. I'm on the latest patch. I am missing Legion. I've tried everything to duplicate the bug on EU. It used to happen when I first installed it, but it fixed it self. I don't know how.

**Comment by NightDweller** [comment]
http://i.imgur.com/MV3sSil.png

This also happens when you have the chat in a corner. Happens on both NA and EU.

**Comment by kaytotes** [comment]
Thanks for this. I've had a look at the first issue and I'm getting the same where the input box moves above tabs. I'm on EU so it's peculiar that you're experiencing it on NA but not EU. I'll look in to this.

It's a little difficult for me to tell what's happening with the second issue, do you mean the text lines slightly overlapping?

**Comment by NightDweller** [comment]
ahh Whispers don't line up with the rest of the chats. If you look closely. You can see the tabs while the chat itself jumps. You can see 'general' right under the 'W' as well as the tab for the whisper right under "it's going fine".

basically the whispers jump if you have the whole chat in a corner. By jump I mean can't be placed correctly with the rest of the tabs/chat.

**Comment by kaytotes** [comment]
Just a heads up I've not forgot about this. Just haven't had the dev time yet

**Comment by NightDweller** [comment]
All good. Just let me know when you get an update out. I don't use curse to install my stuff.

**Comment by kaytotes** [comment]
Combat log fixed with https://github.com/kaytotes/ImprovedBlizzardUI/commit/3c0db937e5f0e5dbf63786c007a59ec7b7694f84

Could not replicate whispers issue.
