### ISSUE TITLE
Chat Whisper Tabs are not stylized

### ISSUE THREAD

**Issue by vividnightmare** [kaytotes/ImprovedBlizzardUI#190]
Really enjoy the stylized chat window offered by this addon.

However, whisper tabs appear to be exempt from this which causes them to be offset from the other tabs.
![example](https://user-images.githubusercontent.com/4257551/125988750-4060e8df-e678-4d54-bcf1-71284972588e.png)

Here the chat window is anchored to the bottom left of the screen and all tabs remove the scroll buttons, except whispers which make those tabs offset and very ugly.

The fonts in these tabs are stylized, but do not seem to obey the Outline Font option.

This is with 3.6.0 on TBCC.

**Comment by kaytotes** [comment]
I had a similar report on this a while back so I'll look into it. Just need to figure out what event / function creates these windows. 

Not much help but I'd recommend using the IM style whispers setting for now that comes under Interface -> Social

![image](https://user-images.githubusercontent.com/7526918/125992759-9afc3e46-305f-4bb6-a200-21fc51ec4401.png)

**Comment by vividnightmare** [comment]
I tried both and it doesn't seem to change anything honestly.

This also originally happened with the combat log as well, but after reloading the UI it settled in with the rest.

Unfortunately when I /reload whisper tabs simply disappear.

**Comment by kaytotes** [comment]
I've been testing a rewrite of my chat code and believe this and a few other issues are resolved. I have tested in Classic, TBC and Retail but will test for the rest of the weekend while i'm playing then will push out a new release.

**Comment by kaytotes** [comment]
Closing. Fixed in 3.7.0
