### ISSUE TITLE
Health Warning cannot be disabled

### ISSUE THREAD

**Issue by vividnightmare** [kaytotes/ImprovedBlizzardUI#191]
Regardless of whether I've checked or unchecked the box for "Health Warning", the warning is always displayed.  Cannot be disabled.

3.6.0 TBCC

**Comment by kaytotes** [comment]
Hmm, how peculiar. I haven't been able to replicate this on Retail but will try TBC too.

**Comment by kaytotes** [comment]
Managed to replicate. Confirmed. Will be resolved in the next release. Thank you @vividnightmare

**Comment by kaytotes** [comment]
https://github.com/kaytotes/ImprovedBlizzardUI/pull/192
