### ISSUE TITLE
Can't join Battleground

### ISSUE THREAD

**Issue by TulleO** [kaytotes/ImprovedBlizzardUI#20]
Hey,
when i Try to Join a Battleground this Message pops out.

![Try to Join Battleground Error](https://cloud.githubusercontent.com/assets/24193138/20642215/4690dc74-b409-11e6-904f-a8cfecdb83e1.PNG)

**Comment by kaytotes** [comment]
I can't seem to replicate this issue. I run battlegrounds pretty often.

Could you disable all over addons and see if the issue persists? And just checking, what version are you using? :)

**Comment by TulleO** [comment]
If i disable all other addons the Issue is still the same. Im running Version 1.3.2

**Comment by kaytotes** [comment]
Thanks for checking.

Please could you install these 2 addons. Attempt to join a Random Battleground and screenshot the error? :)

https://mods.curse.com/addons/wow/bugsack
https://mods.curse.com/addons/wow/bug-grabber

**Comment by TulleO** [comment]
There you go :)

![bugsackerror](https://cloud.githubusercontent.com/assets/24193138/20642460/959e3018-b40f-11e6-8644-9f04e457add8.PNG)

**Comment by kaytotes** [comment]
Thank you very much. I'm raiding right now but will try to take a look just after.

From a quick look at that though I'm stumped because this addon in no way calls any of those functions.

**Comment by TulleO** [comment]
I'm trying to Delete the WTF directory when I get back home and report the outcome!
The Fonts are changed with the Fonts folder but I already deleted the Fonts folder and the Issue still persisted.

**Comment by TulleO** [comment]
Deleted the WTF directory and still the same Error.

![bugsackerror2](https://cloud.githubusercontent.com/assets/24193138/20644187/d524e7c8-b42c-11e6-8e3c-e1be196d0de8.PNG)

**Comment by kaytotes** [comment]
I'm sincerely struggling to reproduce the issue at all.

**Comment by TulleO** [comment]
Can i do anything else? Like Repair my Game or something?

**Comment by kaytotes** [comment]
No need :) Not an issue with your client just how blizzard changed the code. I simply must have misses this change with legion. I'll have a fix up on curse and wowinterface in less than an hour.

**Comment by TulleO** [comment]
Nice!

**Comment by kaytotes** [comment]
"Fixed" with https://github.com/kaytotes/ImprovedBlizzardUI/commit/9215a7a7a4baecd0e9fa6252f7a42533700e42c8

Use the new PvP tab. Uploaded to Curse and WoWInterface so once they accept it you can update :)

**Comment by TulleO** [comment]
works like a charm! Great work dude!
