### ISSUE TITLE
Problem with minimap\quest tracker

### ISSUE THREAD

**Issue by MadExrocist** [kaytotes/ImprovedBlizzardUI#23]
![wowscrnshot_010517_033722](https://cloud.githubusercontent.com/assets/24926499/21664665/092caeda-d2f9-11e6-928b-d5d0f26dcb16.jpg)
![wowscrnshot_010517_033723](https://cloud.githubusercontent.com/assets/24926499/21664668/093045a4-d2f9-11e6-8951-9d87bb0f8e4f.jpg)
![wowscrnshot_010517_033728](https://cloud.githubusercontent.com/assets/24926499/21664666/092dd062-d2f9-11e6-97e1-195af10ead9c.jpg)
![wowscrnshot_010517_033733](https://cloud.githubusercontent.com/assets/24926499/21664667/092e24c2-d2f9-11e6-9fee-e035b41ab210.jpg)
It moves to the left of the screen and just fades. Minimap position starts with centre of the screen and it`s move to the left with pauses. I can`t drag minimap or do something with it

**Comment by kaytotes** [comment]
Please disable all other addons and see if the issue still occurs.
