### ISSUE TITLE
Some Suggestions / TargetClassColor, PlayerClassColor

### ISSUE THREAD

**Issue by Marakuja** [kaytotes/ImprovedBlizzardUI#25]
Hi,
I just want to ask if I can contribute a bit more of my own code snippets to your project. I use them a while now for my UI but I think it would fit nicely into your work, too.

1. Coloring your TargetFrameNameBackground to your Class
![playerclasscolor](https://cloud.githubusercontent.com/assets/5399381/21867282/c88d54f6-d84d-11e6-9183-a0d591730788.JPG)
This would involve creating a Frame, attaching it to the PlayerFrame and colorize it one time at Interface loading (as you are not changing your class until a reload ;) ).

2. Only Color the TargetNameBackground when Target is actually a Player, so you can see if you have a Player in your target or a npc quickly (npcs are colored red or green or yellow by default)
Example of Player
![targetplayer](https://cloud.githubusercontent.com/assets/5399381/21867412/5c000170-d84e-11e6-8a6a-19e7fafb6506.JPG)
Example of NPC(and Focus)
![targetnpcfriendly](https://cloud.githubusercontent.com/assets/5399381/21867422/6184038a-d84e-11e6-8bcc-57c827ba43dc.JPG)
Coding would be really easy as there is only an additional check in ImpBlizzardUI_Unitframes.lua in Line 89 and 94 for "UnitIsPlayer("target")" or "UnitIsPlayer("Focus")"

Tell me what you think of these ideas and let me know if I should do a pull request to this?

**Comment by kaytotes** [comment]
I like colouring the player frame background since the default is pretty boring. Same with having the npc colour changes. 

I don't see why these can't be pull requested.

By the way, I find it real neato that your first foray into Github is through this project. Congrats on your first pull request :)

**Comment by Marakuja** [comment]
Thanks :) I will do the pull request then.

Normally I only code for myself and my own UI but your project was near to my config actually so I thought I get into the wide Internet and into github to share some of the ideas ;) We will see how far it goes from here..

**Comment by kaytotes** [comment]
No idea why this was still open. Closing.

**Comment by kaytotes** [comment]
It's interesting that you posted that @sphvn I was having a look at that yesterday. I'm definitely planning on doing a general overhaul of Unit Frames as part of a big [Pre-Battle for Azeroth Overhaul](https://github.com/kaytotes/ImprovedBlizzardUI/projects/1) .

At the very least i'll be fixing a couple issues as well as adding greater configuration options. Frankly i'm undecided as to whether I'll be doing what I already do by changing the Blizzard Unit Frames, essentially recreating them using oUF or alternatively using that addon as visual inspiration and going from there.

I'm leaving this issue open however feel free to move any discussion over to the new issue i've just created #51

**Comment by sphvn** [comment]
Yeah totally was expecting the issue to stay closed was just curious on thoughts regarding that style, I'll get my dev environment running on my new machine and might have a play with a toggled option

**Comment by kaytotes** [comment]
I've started work on this now and have for the most part finished the
Player Frame with much better config. It's on the Overhaul branch (or at
least will be once I push).
