### ISSUE TITLE
Repositioning unitframes (player, target)?

### ISSUE THREAD

**Issue by Hex1981** [kaytotes/ImprovedBlizzardUI#34]
Hey guys,
just wanted to know, if we can reposition the unitframes? Is there something like "alt-shift-drag"?

Maybe you can help me out, I just want the frames to be a little higher on my screen.

best
Markus

**Comment by kaytotes** [comment]
Currently there is no ingame way of doing this. You would have to edit the LUA [here.](https://github.com/kaytotes/ImprovedBlizzardUI/blob/master/ImpBlizzardUI/modules/ImpBlizzardUI_UnitFrames.lua#L30)
