### ISSUE TITLE
My fork becomes a rewrite - how to properly acknowledge your work

### ISSUE THREAD

**Issue by PatTheMav** [kaytotes/ImprovedBlizzardUI#35]
Hey @kaytotes - as the title says I forked your addon a few days ago as I wanted to change some details about it (e.g. using SharedMediaLib for fonts if available, use OptionalDeps to leave unit frames as they are if another UF addon is loaded, etc.).

But over 2 days I've moved so much code around (e.g. using an internal dispatcher for event handling) and refactored some parts of it that pull requests don't really make sense anymore (I _might_ create some to help here with minor changes), so I'd like to know how to best acknowledge your work as the fork will still the starting point of it all.

(Also I don't intend to throw it up on Curse or something, as I won't have the time to support it for a "real" audience).

**Comment by kaytotes** [comment]
If possible i'd love to take a look at the work you've done but I couldn't find it in any branch on your fork. If you're not intending on having it uploaded anywhere such as Curse or WoWInterface then the only attribution i'd want is a link back to here and just make it fairly obvious that it's a fork.

I'm very interested in what you've done so far particularly the SharedMediaLib for fonts and the internal dispatcher.

**Comment by PatTheMav** [comment]
Sure, I haven't committed anything yet as I'm still working on the base to move forward and try to incorporate as much of the original functionality as possible (right now I have all modules disabled and add/tweak them one by one.

Might take a while though as I'm playing more HotS than WoW at the moment.. 😬 I'll ping you once I've committed a new branch though.
