### ISSUE TITLE
Probleme with WoW Menu Bar

### ISSUE THREAD

**Issue by bombzy** [kaytotes/ImprovedBlizzardUI#37]
Hello guys ! This addon is awesome but I  have just one request to be perfect for me.

Can we have an option to toggle off the modifications of the wow menu bar and the cast bars ?
![2017-08-15 09_55_11-wowscrnshot_081517_095154](https://user-images.githubusercontent.com/6500915/29306960-157ffa4c-81a0-11e7-89e1-f97dc4bd7e1e.png)

Because I use this bar a lot and I need it please :) <3

That's all I need please <3

**Comment by kaytotes** [comment]
You can toggle a view of the bags by right clicking the minimap however I will not be re-adding the other micro-menu options as the minification of the action bars as a core part of the addon.
