### ISSUE TITLE
Minimap moving around on 1920x1080 resolution

### ISSUE THREAD

**Issue by vhusker** [kaytotes/ImprovedBlizzardUI#38]
Just downloaded and installed this today after giving up on zPerl after the changes they've made.  I love everything about this except that when I login the minimap starts in the middle of screen, eventually makes it way over to the far left and then if I open up the system menu (as one example) it just disappears.  If I run /console reloadui it comes back to the middle of my screen.

![image](https://user-images.githubusercontent.com/6845844/29994991-8d23f9e8-8fa3-11e7-8fb2-0ef47d94a512.png)

And after looking at the above screenshot it appeared to me that maybe the TitanPanel addon was in the way and causing problems.  I disabled that add-on and success!  
![image](https://user-images.githubusercontent.com/6845844/29995003-188f8182-8fa4-11e7-86b2-94cf0dc453a0.png)

Any ideas what's going on with TitanPanel blocking it's functionality and what I can do so that I can use both at the same time?

**Comment by vhusker** [comment]
As a follow up I even moved the Titan Panel bar to the bottom of my screen and the minimap is still doing weird stuff.

![image](https://user-images.githubusercontent.com/6845844/29995062-77f3399c-8fa5-11e7-98b2-1960b970f109.png)

**Comment by kaytotes** [comment]
I sincerely have no idea what causes Titan Panel to do this but it's a known incompatibility. I'm not going to go digging around in another developers code to try and figure out what the issue is. This will not be fixed especially since I do not use Titan Panel myself.
