### ISSUE TITLE
Option to enable micro bar

### ISSUE THREAD

**Issue by mattarolla** [kaytotes/ImprovedBlizzardUI#39]
I would like an option to enable the micro bar. It might fit on the bottom right of the UI. I like having the microbar available during pet battles so I can check what rarity I have of the pet I'm fighting and if it's disabled it doesn't appear in the pet battle UI.

**Comment by kaytotes** [comment]
I'll need to double check but the right click menu for the minimap should work. I wonder if it would be better to make this more obvious.
