### ISSUE TITLE
Impossibility to unlock unitframe

### ISSUE THREAD

**Issue by Opachop** [kaytotes/ImprovedBlizzardUI#42]
First of all, excuse my english
Everytime i try to unlock the unitframe and to move it, i got an error report.
I want to know if it's commun bug of the addons that will be fix or if it's a isolated problem ?

**Comment by kaytotes** [comment]
I'll have a look into why it's spamming the error but either way being unable to unlock and move the unit frames is intended. They are where they are supposed to be.
