### ISSUE TITLE
Focus frame and few others.

### ISSUE THREAD

**Issue by sipso** [kaytotes/ImprovedBlizzardUI#46]
Hi, i love the simplicity of your addon. But for my taste it could use some customization options.
The major issue i have is with focus frame. I use Prat 3.0 for my chat. When trying to set a focus target i get Prat 3.0 error and focus doesn't appear until i disable Prat. As a tank i kinda need focus target :)

About customizations - moving frames would be fantastic, and if you want to stick with your design, at least give us "tick" options like "lower unit frame position". "Hide when out of combat" is a must. Would also love to see hp numbers converted into Millions.

**Comment by kaytotes** [comment]
I'm unsure why Prat 3.0 is causing that error and honestly it's far too big of an addon for me to go digging in to attempt to figure out why. This UI is the only addon I have installed (why it was created) so I don't go out of my way to support external addons.

The positioning configuration is definitely something that is on my todo list with an issue open #43  I haven't managed to pencil in the time to get stuck into this yet but it will get done eventually.

**Comment by kaytotes** [comment]
Going to close this and point at #51 instead. The Prat issue may or may not be fixed with the new re-write but if not I won't be going out of my way to support it.
