### ISSUE TITLE
Localisation Improvements / Changes

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/ImprovedBlizzardUI#50]
During the process of the BfA overhaul I am going to be adding a bunch of new strings as well as attempting to improve documentation. 

The new template will be created as I add each new feature that requires a string then once the overhaul is nearing completion I'll have to try and salvage whatever I can from the previous localisation files.

**Comment by kaytotes** [comment]
The Overhaul is now feature complete and as such will need localising. I've had a look at what can be ported over and what can't and frankly I think this would need to basically just be done again because being 1/4 done is worse than not at all.

`ptBR` was originally submitted by @cyberdisarray
`deDE` was originally submitted by @Marakuja and @ben2k1690 
`ruRU` i'm unsure who submitted it but this is the commit from 3 years ago https://github.com/kaytotes/ImprovedBlizzardUI/commit/db6fe47f5325394796ac77d9141efdf1996450f0

**Comment by ben2k1690** [comment]
I will try to localize it to german again :)

2018-03-11 14:44 GMT+01:00 Kaytotes <notifications@github.com>:

**Comment by kaytotes** [comment]
That would be fantastic if you could @ben2k1690

**Comment by kaytotes** [comment]
Wow thank you very much Blader. I'll see about getting that integrated.
