### ISSUE TITLE
Unit Frames Overhaul

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/ImprovedBlizzardUI#51]
I need to fix a couple issues as well as adding greater configuration options. Frankly i'm undecided as to whether I'll be doing what I already do by changing the Blizzard Unit Frames, essentially recreating them using [oUF](https://github.com/oUF-wow/oUF) or alternatively using [Unit Frames Improved](https://wow.curseforge.com/projects/unitframesimproved) as visual inspiration and going from there.

**Comment by sphvn** [comment]
This is looking pretty good! :+1:

**Comment by kaytotes** [comment]
Done some more tweaking with this. Styled and positioned the focus frame relative to the player frame and also based on the overall "global" scale in configuration, class colours included of course. Also added a consistent font across unit frames.

![screenshot_1](https://user-images.githubusercontent.com/7526918/35473400-f4ae1790-0377-11e8-9442-bd18c3603d15.png)

Going to swap over to doing some action bar work next I think before doing Party and Boss frames as I can't stand doing dungeons with the default positioning.

**Comment by sphvn** [comment]
Just making a note to check status bar text with these updates for myself

**Comment by kaytotes** [comment]
@sphvn been watching a load of BfA Alpha footage today and the numbers are squished a huuuuge amount. 500 - 1500 for an ability. Due to this as well as the item level squish I won't be making any changes like truncating the current numbers. Consider it a maybe once I've done the rest or alternatively feel free to pull this branch and fiddle around.

**Comment by sphvn** [comment]
Wasn't implying a reformat sorry, just to check myself that when the status text is turned on it fits well with the name / bar positioning as is. :)

**Comment by sphvn** [comment]
![world of warcraft 9_02_2018 10_42_00 pm](https://user-images.githubusercontent.com/1013429/36026335-ab9b630a-0dea-11e8-9ea9-95311c41664a.png)

Only clipping I see is on the pet frame, albeit this won't bother me as I don't play a class with pets currently. Was checking for pet / stance bar overlaps.

**Comment by kaytotes** [comment]
@sphvn Interestingly the overlap of the pet frame appears to be a part of Blizzards UI, at least in the case of Hunters. I don't have a DK to test on. Does this overlapping of pet text over runes occur when just using the default UI?

![image](https://user-images.githubusercontent.com/7526918/36050040-d2b657fa-0ddc-11e8-8464-bd64cb09d7a3.png)

**Comment by sphvn** [comment]
@kaytotes Yeah it certainly does happen on the default UI, ignore me on this one 👍

**Comment by kaytotes** [comment]
@sphvn That's great I thought as much. Will get round to doing party frames and boss frames this weekend then this can be closed off.

**Comment by kaytotes** [comment]
Party frames are now re positioned and styled with matching font. They also now grow upwards so that it looks better. Scale is essentially the primary scale + 0.2.

Done a few dungeons for testing but think it's stable thus far. 

![screenshot_1](https://user-images.githubusercontent.com/7526918/36354986-28f4c1c6-14d4-11e8-8b49-3cf23531a9d3.png)
![screenshot_2](https://user-images.githubusercontent.com/7526918/36354988-2be8e5e2-14d4-11e8-9807-f17d6f715fac.png)

**Comment by kaytotes** [comment]
Done testing and happy with this. Marking as complete.
