### ISSUE TITLE
Player Unit Frame Toggle?

### ISSUE THREAD

**Issue by Cryonyte** [kaytotes/ImprovedBlizzardUI#52]
Hey there, first off thank you for creating this UI - it's fantastic!

I have been using it for over a week and I've really grown towards this look for some reason, even though before that I was using RealUI which changes everything haha.

Anyway my current request would be is it possible to have the player unit frame to disappear when I am not in combat? 

If there is a way for me to do it if you don't have time for it then do tell then I'll try my hand at it. I am a noob in WoW 'modding' but I have experience in modding stuff like Skyrim!

Cheers!

**Comment by kaytotes** [comment]
I'm currently in the process of [overhauling the UI ](https://github.com/kaytotes/ImprovedBlizzardUI/projects/1) and as part of that i'm taking a good look at the [unit frames and general configuration](https://github.com/kaytotes/ImprovedBlizzardUI/issues/51). This is a feature that I would like myself so I'll definitely be looking into it. I'm expecting the re-write to be done in about a week or so.

**Comment by sphvn** [comment]
Can probably close this as it's in the other issue and working on the feature branch.

**Comment by kaytotes** [comment]
@sphvn is correct. Closing this now and diverting discussion to #51
