### ISSUE TITLE
Module: One Bag

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/ImprovedBlizzardUI#60]
I've decided that this will not be part of the initial launch of the BfA Overhaul. This is going to be an extremely sizeable module and I need to do a lot of research to figure out how best to build this and also learn the relevant Blizzard API's.

However this is not completely off the cards and I will be eventually working on this it just simply won't be in the next public release.

**Comment by 10leej** [comment]
Blooblahguy has an excellent example of a lightweight method for making a one bag frame with bdBags http://www.wowinterface.com/downloads/info21055-bBag.html

**Comment by kaytotes** [comment]
I've had a ganders at the code for pretty much every bag addon I could find including bdBag. Was an interesting prod around but the dependency on bdCore meant I didn't dig far as I can't be bothered juggling between the two attempting to piece together another developers code.

I'm definitely going to be revisiting this however in the mean time I've found [Baud Bag](https://www.curseforge.com/wow/addons/baud-bag) to fit both the functionality and style requirements I had in mind so have just been using that. Some niggles with it that I'd still want to change so this is far from off the cards.
