### ISSUE TITLE
Kill Feed Raid Error

### ISSUE THREAD

**Issue by kaytotes** [kaytotes/ImprovedBlizzardUI#64]
Whilst going through Antorus on my main yesterday I get a LUA error from the Kill Feed quite a few times. This seemed to occur when a player in the raid was killed by an NPC but I don't have more specifics than that. Interestingly enough, did some testing on a healer alt in LFR and intentionally let people die but couldn't recreate it at that point.

Error comes from [here](https://github.com/kaytotes/ImprovedBlizzardUI/blob/develop/modules/frames/killfeed.lua#L58) specifically.

![screenshot_4](https://user-images.githubusercontent.com/7526918/37306420-9743951e-262f-11e8-9c6f-cc3a590ba150.png)

However, despite pointing at that line my gut feeling is that this may be caused by taint elsewhere.

**Comment by sphvn** [comment]
> did some testing on a healer alt in LFR and intentionally let people die

All for the greater cause! 

Will try and see if I can replicate this myself also.

**Comment by kaytotes** [comment]
Definitely an issue in raids when people died. But it's damned hard to work out the root cause. Not sure specifically why that function is failing.
