### ISSUE TITLE
Focus Frame Elite Border copied from target

### ISSUE THREAD

**Issue by xMarok** [kaytotes/ImprovedBlizzardUI#65]
The focus frame will have an elite border texture if your target also has the texture.

Targeting myself: [Image](https://i.imgur.com/7F7Ev3j.jpg)
Targeting an elite: [Image](https://i.imgur.com/9V70dSh.jpg)

This happens no matter who/what your focus target is. The inverse happens as well. That is, if your focus is an Elite, targeting a non-elite will remove the texture.

**Comment by kaytotes** [comment]
That's an interesting one. I'll take a look at this tomorrow.
