### ISSUE TITLE
ArtifactWatchBar overlapping the EXP bar (1440p)

### ISSUE THREAD

**Issue by shinnova** [kaytotes/ImprovedBlizzardUI#66]
### Expected behavior
Artifact, rep and exp bars can all be visible at the same time

### Actual behavior
Artifact bar overlaps the exp bar:
![screenshot_20180322_125414](https://user-images.githubusercontent.com/12647312/37769198-814a4d5e-2dd0-11e8-91ad-959fae731365.png)

### Steps to reproduce
Have more than one bar displaying while using this addon

I don't know if this is related to having a 1440p resolution or not.

**Comment by shinnova** [comment]
I am level 101. I was wrong about the rep bar, that gets properly destroyed. After taking a quick look at the code, it seems that the exp bar only gets destroyed if you're max level? And the exp bar and artifact bar seem to then be put in exactly the same spot.

**Comment by fosspill** [comment]
I'm also experiencing this on my level 108 char.
EXP bar and Artifact are overlapping. Tried with a completely clean install. Even with no other addons they are still overlapping.

I believe shinnova is talking about the function here:
https://github.com/kaytotes/ImprovedBlizzardUI/blob/2decd922feb9959e60e6d9c6c34943a5765df3d3/modules/bars/actionbars.lua#L71

**Comment by kaytotes** [comment]
Yep this is an issue that went un-noticed as I don't have any characters within that bracket of having both exp and artifacts. Considering artifacts are going away at the end of the expansion I think I'll prioritise showing exp over artifact power whilst questing.

**Comment by fosspill** [comment]
I support that :)
