### ISSUE TITLE
Focus frame target's target and castbar overlapping

### ISSUE THREAD

**Issue by Hessutar** [kaytotes/ImprovedBlizzardUI#69]
Hey Guys.

First of all, this is the best UI addon I've come across for a long time. Nice work!

Anyhow I've stumbled on a minor problem on the positioning of focus frame target's target + cast bar. They seem to overlap with the player unit frame. Picture below.

![screen shot 2018-03-26 at 19 43 13](https://user-images.githubusercontent.com/5693510/37929732-6e56f108-3149-11e8-8f7b-3a16f44358f5.png)

The problem could be solved by adjusting the focus frame by a little but they seemed to be locked by the addon.

Again thank you for the splendid addon!

**Comment by xMarok** [comment]
Personally, I really like where the focus frame is by default. A potential solution would be to move the cast bar in the little space right below the focus' mana bar. Like this:
![](https://i.imgur.com/TFwkb14.png)

**Comment by kaytotes** [comment]
Thanks for this issue report. I've tweaked the positioning of this as well as sorted the mismatched font. Had to bump it up and to the right to be a bit more directly above the player to accommodate the party frame too.

**Comment by xMarok** [comment]
I added the changes manually just to test them out, and it looks like the `-- Style Font` part you added is breaking the styling/position of the focus frame.
With just position change: ![](https://i.imgur.com/Ckypp2c.jpg)
With both: ![](https://i.imgur.com/Tsv8r29.jpg)

**Comment by kaytotes** [comment]
I'm not able to replicate this.

**Comment by xMarok** [comment]
Strange. After updating the addon and overwriting my version, the focus frame works as expected despite the files being exactly the same. Oh well.
