### ISSUE TITLE
Styled frames seem to turn on when option is off

### ISSUE THREAD

**Issue by maxhuebler** [kaytotes/ImprovedBlizzardUI#71]
I can't explain how exactly, but when I have the styled frames turned off sometimes throughout playing or after a loading screen, the addon reverts to using the styled frames. I want to say this happens when colored player class is disabled, it becomes enabled eventually.

**Comment by kaytotes** [comment]
I fixed this a couple days ago here https://github.com/kaytotes/ImprovedBlizzardUI/commit/7868b3a4d93bbb06191f3b194cc30c48387d5a65 and will have this on WoWInterface and Curse in around an hour. Wanted to test other changes before release.

**Comment by kaytotes** [comment]
The fix for this is now uploaded and awaiting approval on both sites.
