### ISSUE TITLE
Unable to display Chinese

### ISSUE THREAD

**Issue by tianyu94** [kaytotes/ImprovedBlizzardUI#73]
I am a player in China. I particularly like this plugin, but I cannot display Chinese characters normally. Hope to solve it, thank you.

e.g. 魔兽世界  -->  ????

**Comment by kaytotes** [comment]
I think the only solution to this would be to replace `media/impfont.ttf` to one that works. If you do however find one that works please link it to me here so that I can perhaps make this work by default.

**Comment by hmmabc** [comment]
replace media/impfont.ttf with any Chinese font, it works.

**Comment by kaytotes** [comment]
If you provide me one I'd be happy to do a localisation check and swap it out automatically for you.
