### ISSUE TITLE
Want to be able to move some frames 

### ISSUE THREAD

**Issue by lynspottery** [kaytotes/ImprovedBlizzardUI#74]
I just started using this UI and am fairly pleased with it, however, I wonder if there is a way to unlock where some frames are so that they can be dragged to a different location on my screen?

For instance, I much prefer my character & pet frames to be up in the left hand corner out of the way rather than just above my hot bars but I cannot find any way to unachor them to move them to a more desirable location.

**Comment by kaytotes** [comment]
There is currently no supported way to do this through a menu. Moving them to their current position is intended.

For now tweaking the values `primaryOffsetX` and `primaryOffsetY` in `config.lua` will move them. This is parented around the center of the frame.

**Comment by VerySvensk** [comment]
If i wanted to move the frames like this (https://imgur.com/a/NQdwfEo) what primaryOffsetX and primaryOffsetY numbers would i have to input?
