### ISSUE TITLE
Chat imput box cannot be moved?

### ISSUE THREAD

**Issue by lynspottery** [kaytotes/ImprovedBlizzardUI#75]
I have tried to get my chat input box moved back down to the bottom of the chat frame without success.

Why can't I do this simple adjustment?  Is there some trick to getting this input line moved from top to bottom? #74

**Comment by kaytotes** [comment]
There is no configuration for this. Perhaps it will be pull requested by someone.

In the mean time remove these lines of code https://github.com/kaytotes/ImprovedBlizzardUI/blob/develop/modules/misc/chat.lua#L81-L88

**Comment by sphvn** [comment]
@kaytotes Want to assign me to this one, seems like a super quick change.

**Comment by kaytotes** [comment]
Feel free and pull request however as of a couple days ago just moved to a new place without internet yet, living off of tethered data. Won't be merging and pushing onto Curse or WoWInterface until I have full access.

**Comment by sphvn** [comment]
I'm in the middle of moving myself also, so all good.

**Comment by kaytotes** [comment]
@lynspottery Finally in the land of the living. I'll be taking a look at this tonight or tomorrow.
