### ISSUE TITLE
JoinBattlefield error

### ISSUE THREAD

**Issue by imarctic** [kaytotes/ImprovedBlizzardUI#76]
Posted directly from error box, happened after clicking Join Battle on Random Battlegrounds. Issue resolves after reload but comes back sometimes.

Date: 2018-04-14 13:39:27
ID: 1
Error occured in: AddOn: ImprovedBlizzardUI
Count: 1
Message: Error: AddOn ImprovedBlizzardUI attempted to call a forbidden function (JoinBattlefield()) from a tainted execution path.
Debug:
   [C]: JoinBattlefield()
   Blizzard_PVPUI\Blizzard_PVPUI.lua:611: HonorFrame_Queue()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  AdiBags, vv1.9.8
  AdiBagsHearthstones, v7.3-release1
  AdiBagsLegionFilters, v1.6.7
  ArtifactButton, v5.0
  BadBoy, vv7.3.119
  BigDebuffs, vv6.4
  DBMCore, v7.3.26
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  GatherMate2, v1.41
  GladiatorlosSA2, v1.17
  Gladius, v5.2.3
  ImprovedBlizzardUI, v2.1.0
  MasterPlanA, vA
  OmniBar, vv8.1
  PetBattleTeams, v3.3.9
  PetTracker, v7.3.0
  PetTrackerBreeds, v7.3.0
  PetTrackerConfig, v7.3.0
  PetTrackerSwitcher, v7.3.0
  PetTrackerUpgrades, v7.3.0
  Prat30, vr1082      
  Prat30Libraries, v
  SlideBar, v7.3.1 (<%codename%>)
  TidyPlatesThreatPlates, v8.6.5
  TradeSkillMaster, ved2ce3c
  TradeSkillMasterAppHelper, va8f2b46
  WorldQuestTracker, v
  XLoot, v7.3-3
  XLootFrame, v7.3-3
  XLootGroup, v7.3-3
  XLootMaster, v7.3-3
  XLootMonitor, v7.3-3
  ZygorGuidesViewer, v6.1
  BlizRuntimeLib_enUS v7.3.5.70300 <none>
  (ck=4d1)

**Comment by kaytotes** [comment]
Been moving into a new place with limited internet. Getting around to this now. Thank you for the report I'll investigate.
