### ISSUE TITLE
ArtifactWatchBar

### ISSUE THREAD

**Issue by val1n** [kaytotes/ImprovedBlizzardUI#9]
The ArtifactWatchBar gets repositioned but not resized. So it is far too long. Oh and the MultiBarBottomLeft and MultiBarBottomRight are overlapping the ArtifactWatchBar.

![wowscrnshot_062016_130439](https://cloud.githubusercontent.com/assets/453772/16192271/9494f4c6-36e8-11e6-995b-7092420d8e82.jpg)

**Comment by kaytotes** [comment]
Thanks for this. Will try my best to fix it up on the PTR but won't be able to properly test until I can get full Beta access.

**Comment by ben2k1690** [comment]
I will test it as good as i can (i have beta access) so if you need someone to test let us have a talk

**Comment by val1n** [comment]
Since I have beta access as well, I would happily help you

**Comment by ben2k1690** [comment]
I'm currently at work so i can't test my first try to move the bar: https://github.com/ben2k1690/ImprovedBlizzardUI/tree/ArtifactWatchBar-Dev

Maybe if @val1n could try it?

**Comment by val1n** [comment]
The ArtifactWatchBar is centred. But the texture kept the original width. But just the texture .. to get the tooltip (and the text) I have to be in the 512 pixels. The left and right parts are just for deco. I mean I can see how much Artifact Power my weapon has, but as I said the tooltip will only be displayed in the 512 pixel range.
Oh and in the screenshot I have moved it 8 pixels ... and disabled the Bottom Left Bar
`ModifyBasicFrame(ArtifactWatchBar, "TOP", nil, -256, 8, nil);`

![wowscrnshot_062116_140831](https://cloud.githubusercontent.com/assets/453772/16229181/d50463a6-37bb-11e6-897c-5e887b955f28.jpg)

**Comment by ben2k1690** [comment]
It's a first step in the right direction.
I will try to get a custom bar when i am at home again. Currently at the work i'm not able to play the game :D

**Comment by kaytotes** [comment]
Hold off a couple hours until I'm back from work. As soon as I get in I'll push my latest changes as I've considerably tweaked these bars. Still have an issue with them occasionally resetting during combat (Seems to be just PvP combat?)

**Comment by ben2k1690** [comment]
In which way are they resetting? During combat or after combat when you gain ep/honor?

**Comment by val1n** [comment]
#8 mentioned it. And since I have never experienced this, it seems that only PvP combat is affected by this.

**Comment by kaytotes** [comment]
Occurs during combat. Seems to be only Honor related but I haven't quite yet tracked down exactly where in Blizzards code these are being reset.

#8 was the original issue but it seems to affect Honor, Rep and Artifact bars so I'll expand the issue once I get back home.

`hooksecurefunc("MainMenuBar_UpdateExperienceBars", MainMenuBar_UpdateExperienceBars_Hook);` corrects the issue once any of the bars are updated out of combat.

**Comment by kaytotes** [comment]
Let me know if this is any better with https://github.com/kaytotes/ImprovedBlizzardUI/commit/6f0143ba65a2ed79dc447c05d7478d257d6bcff3 on the development branch. Resetting still occurs in PvP combat but generally tweaked these bars.

**Comment by ben2k1690** [comment]
Just logged in and at fist it seems fine
![wowscrnshot_062116_184150](https://cloud.githubusercontent.com/assets/1721846/16238221/f3cf407a-37df-11e6-8cbb-a5e42484f2d9.jpg)

**Comment by kaytotes** [comment]
Hmm, looks like it's shunted up as if it's expecting either an Honor or Rep bar above the artifact bar. Maybe the artifact bar automatically shifts things upwards and I wasn't aware?

**Comment by ben2k1690** [comment]
it doesn't when you are not reposition it. I can put it a bit lower and test it if you want

**Comment by kaytotes** [comment]
Feel free.

**Comment by ben2k1690** [comment]
The Bars are just 10px to high. If you adjust them it fits perfectly
![wowscrnshot_062116_185441](https://cloud.githubusercontent.com/assets/1721846/16238695/b6aa35c2-37e1-11e6-9a08-2698f9772f47.jpg)

**Comment by kaytotes** [comment]
It breaks on characters that have no exp bar or artifact bar. (Eg capped on PTR), would be fine once Legion arrives but now / after it will break again.

**Comment by kaytotes** [comment]
Aight, pretty sure this covers all bases https://github.com/kaytotes/ImprovedBlizzardUI/commit/2a9b9ab9cfc4963dbd329574dbbd22f98c2df098

**Comment by ben2k1690** [comment]
I'm going to test it now

**Comment by kaytotes** [comment]
Considering this fixed with https://github.com/kaytotes/ImprovedBlizzardUI/commit/01e886becf4a9b6631a213ba9fc5b40630423ec5

#8 still exists but it's a seperate issue.
