### ISSUE TITLE
On combat begin/end the UI gets partially overridden by blizz default ui

### ISSUE THREAD

**Issue by JonSnowbd** [kaytotes/ImprovedBlizzardUI#96]
https://i.imgur.com/ZqBaR4w.png

Like this, the bottom left bar gets smushed onto the main action bar to the right.

This happens randomly on combat and ends some time after combat

Also side issue; the first 5 icons of the bottom left bar are invisible unless something is on it, inconsistent with actual settings or even the rest of the bar, its very weird

**Comment by kaytotes** [comment]
Noticed this myself last night mid raid. I'm investigating tonight as this
is high high priority.

**Comment by kaytotes** [comment]
Further information here #98
